trigger:
  - main

pool:
  name: "Default"

variables:
  sshConnection: "MyVmSSH"
  targetFolder: "/var/www/html"

steps:
  - checkout: self

  - task: SSH@0
    inputs:
      sshEndpoint: $(sshConnection)
      runOptions: "commands"
      commands: |
        set -e
        echo "Actualizando paquetes..."
        sudo apt-get update -y
        echo "Instalando Apache..."
        sudo apt-get install -y apache2
        echo "Creando carpeta destino si no existe..."
        sudo mkdir -p $(targetFolder)
        echo "Configurando la página HTML..."
        echo 'Hola Mundo, despliegue de máquina virtual desde Azure DevOps Caro - Briceño - Davila' | sudo tee $(targetFolder)/index.html
        echo "Reiniciando Apache..."
        sudo systemctl restart apache2
        echo "Despliegue completado."
